// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: fileflags/hooks.proto

package fileflags

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// MyHooksMessageModel is the GORM model for fileflags.MyHooksMessage.
type MyHooksMessageModel struct {
}
