// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          v3.17.3
// source: fileflags/model.proto

package fileflags

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb/v2"
)

// MyMessageModel is the GORM model for fileflags.MyMessage.
type MyMessageModel struct {
}
