// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          v3.17.3
// source: fileflags/validate.proto

package fileflags

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb/v2"
)

// MyValidateMessageModel is the GORM model for fileflags.MyValidateMessage.
type MyValidateMessageModel struct {
}
