// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: options/options.proto

package options

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)
