// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: options/options.proto

package options

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyEnum int32

const (
	MyEnum_MY_ENUM_UNSPECIFIED MyEnum = 0
)

// Enum value maps for MyEnum.
var (
	MyEnum_name = map[int32]string{
		0: "MY_ENUM_UNSPECIFIED",
	}
	MyEnum_value = map[string]int32{
		"MY_ENUM_UNSPECIFIED": 0,
	}
)

func (x MyEnum) Enum() *MyEnum {
	p := new(MyEnum)
	*p = x
	return p
}

func (x MyEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MyEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_options_options_proto_enumTypes[0].Descriptor()
}

func (MyEnum) Type() protoreflect.EnumType {
	return &file_options_options_proto_enumTypes[0]
}

func (x MyEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MyEnum.Descriptor instead.
func (MyEnum) EnumDescriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{0}
}

type MyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field_1 string `protobuf:"bytes,1,opt,name=field_1,json=field1,proto3" json:"field_1,omitempty"`
	// Types that are assignable to Oneof:
	//	*MyMessage_Field_2
	//	*MyMessage_Field_3
	Oneof isMyMessage_Oneof `protobuf_oneof:"oneof"`
}

func (x *MyMessage) Reset() {
	*x = MyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_options_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyMessage) ProtoMessage() {}

func (x *MyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_options_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyMessage.ProtoReflect.Descriptor instead.
func (*MyMessage) Descriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{0}
}

func (x *MyMessage) GetField_1() string {
	if x != nil {
		return x.Field_1
	}
	return ""
}

func (m *MyMessage) GetOneof() isMyMessage_Oneof {
	if m != nil {
		return m.Oneof
	}
	return nil
}

func (x *MyMessage) GetField_2() string {
	if x, ok := x.GetOneof().(*MyMessage_Field_2); ok {
		return x.Field_2
	}
	return ""
}

func (x *MyMessage) GetField_3() int32 {
	if x, ok := x.GetOneof().(*MyMessage_Field_3); ok {
		return x.Field_3
	}
	return 0
}

type isMyMessage_Oneof interface {
	isMyMessage_Oneof()
}

type MyMessage_Field_2 struct {
	Field_2 string `protobuf:"bytes,2,opt,name=field_2,json=field2,proto3,oneof"`
}

type MyMessage_Field_3 struct {
	Field_3 int32 `protobuf:"varint,3,opt,name=field_3,json=field3,proto3,oneof"`
}

func (*MyMessage_Field_2) isMyMessage_Oneof() {}

func (*MyMessage_Field_3) isMyMessage_Oneof() {}

type MyMethodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MyMethodRequest) Reset() {
	*x = MyMethodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_options_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyMethodRequest) ProtoMessage() {}

func (x *MyMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_options_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyMethodRequest.ProtoReflect.Descriptor instead.
func (*MyMethodRequest) Descriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{1}
}

type MyMethodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MyMethodResponse) Reset() {
	*x = MyMethodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_options_options_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyMethodResponse) ProtoMessage() {}

func (x *MyMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_options_options_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyMethodResponse.ProtoReflect.Descriptor instead.
func (*MyMethodResponse) Descriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{2}
}

var File_options_options_proto protoreflect.FileDescriptor

var file_options_options_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x1a, 0x15, 0x67, 0x6f, 0x72, 0x6d, 0x2f, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x01, 0x0a, 0x09, 0x4d, 0x79, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x04, 0xb2, 0xbb, 0x18, 0x00, 0x52, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x31, 0x12, 0x19, 0x0a, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x12,
	0x19, 0x0a, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x3a, 0x0f, 0xaa, 0xbb, 0x18, 0x0b,
	0x2a, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0d, 0x0a, 0x05, 0x6f,
	0x6e, 0x65, 0x6f, 0x66, 0x12, 0x04, 0xba, 0xbb, 0x18, 0x00, 0x22, 0x11, 0x0a, 0x0f, 0x4d, 0x79,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a,
	0x10, 0x4d, 0x79, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2a, 0x2d, 0x0a, 0x06, 0x4d, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x13, 0x4d,
	0x59, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x1a, 0x04, 0xca, 0xbb, 0x18, 0x00, 0x1a, 0x04, 0xc2, 0xbb, 0x18, 0x00,
	0x32, 0x58, 0x0a, 0x09, 0x4d, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a,
	0x08, 0x4d, 0x79, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x18, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x4d, 0x79, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4d, 0x79,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x04,
	0xda, 0xbb, 0x18, 0x00, 0x1a, 0x04, 0xd2, 0xbb, 0x18, 0x00, 0x42, 0x4b, 0x5a, 0x45, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78,
	0x36, 0x34, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f,
	0x72, 0x6d, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65,
	0x6e, 0x2d, 0x67, 0x6f, 0x72, 0x6d, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0xa2, 0xbb, 0x18, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_options_options_proto_rawDescOnce sync.Once
	file_options_options_proto_rawDescData = file_options_options_proto_rawDesc
)

func file_options_options_proto_rawDescGZIP() []byte {
	file_options_options_proto_rawDescOnce.Do(func() {
		file_options_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_options_options_proto_rawDescData)
	})
	return file_options_options_proto_rawDescData
}

var file_options_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_options_options_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_options_options_proto_goTypes = []interface{}{
	(MyEnum)(0),              // 0: options.MyEnum
	(*MyMessage)(nil),        // 1: options.MyMessage
	(*MyMethodRequest)(nil),  // 2: options.MyMethodRequest
	(*MyMethodResponse)(nil), // 3: options.MyMethodResponse
}
var file_options_options_proto_depIdxs = []int32{
	2, // 0: options.MyService.MyMethod:input_type -> options.MyMethodRequest
	3, // 1: options.MyService.MyMethod:output_type -> options.MyMethodResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_options_options_proto_init() }
func file_options_options_proto_init() {
	if File_options_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_options_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_options_options_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyMethodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_options_options_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyMethodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_options_options_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*MyMessage_Field_2)(nil),
		(*MyMessage_Field_3)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_options_options_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_options_options_proto_goTypes,
		DependencyIndexes: file_options_options_proto_depIdxs,
		EnumInfos:         file_options_options_proto_enumTypes,
		MessageInfos:      file_options_options_proto_msgTypes,
	}.Build()
	File_options_options_proto = out.File
	file_options_options_proto_rawDesc = nil
	file_options_options_proto_goTypes = nil
	file_options_options_proto_depIdxs = nil
}
