// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm 1.0.0
// 	protoc          (unknown)
// source: fileflags/crudflag.proto

package fileflags

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// CrudFlagMessageModel is the GORM model for fileflags.CrudFlagMessage.
type CrudFlagMessageModel struct {
}

// ToProto converts a CrudFlagMessageModel to its protobuf representation.
func (m *CrudFlagMessageModel) ToProto() (*CrudFlagMessage, error) {
	p := new(CrudFlagMessage)
	return p, nil
}

// ToModel converts a CrudFlagMessage to its GORM model.
func (p *CrudFlagMessage) ToModel() (*CrudFlagMessageModel, error) {
	m := new(CrudFlagMessageModel)
	return m, nil
}
