// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: fileflags/crudflag.proto

package fileflags

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// CrudFlagMessageModel is the GORM model for fileflags.CrudFlagMessage.
type CrudFlagMessageModel struct {
}

// AsProto converts a CrudFlagMessageModel to its protobuf representation.
func (m *CrudFlagMessageModel) AsProto() (*CrudFlagMessage, error) {
	x := new(CrudFlagMessage)
	return x, nil
}

// AsModel converts a CrudFlagMessage to its GORM model.
func (x *CrudFlagMessage) AsModel() (*CrudFlagMessageModel, error) {
	m := new(CrudFlagMessageModel)
	return m, nil
}
