// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: fileflags/crud.proto

package fileflags

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// ImplicitCRUDModel is the GORM model for fileflags.ImplicitCRUD.
type ImplicitCRUDModel struct {
}

// AsProto converts a ImplicitCRUDModel to its protobuf representation.
func (m *ImplicitCRUDModel) AsProto() (*ImplicitCRUD, error) {
	x := new(ImplicitCRUD)
	return x, nil
}

// AsModel converts a ImplicitCRUD to its GORM model.
func (x *ImplicitCRUD) AsModel() (*ImplicitCRUDModel, error) {
	m := new(ImplicitCRUDModel)
	return m, nil
}
