// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: fileflags/crud.proto

package fileflags

import (
	context "context"
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// ImplicitCRUDModel is the GORM model for fileflags.ImplicitCRUD.
type ImplicitCRUDModel struct {
}

// ToProto converts a ImplicitCRUDModel to its protobuf representation.
func (m *ImplicitCRUDModel) ToProto() (*ImplicitCRUD, error) {
	x := new(ImplicitCRUD)
	return x, nil
}

// ToModel converts a ImplicitCRUD to its GORM model.
func (x *ImplicitCRUD) ToModel() (*ImplicitCRUDModel, error) {
	m := new(ImplicitCRUDModel)
	return m, nil
}

func CreateImplicitCRUDModel(ctx context.Context) {}

func GetImplicitCRUDModel(ctx context.Context) {}

func ListImplicitCRUDModel(ctx context.Context) {}

func UpdateImplicitCRUDModel(ctx context.Context) {}

func DeleteImplicitCRUDModel(ctx context.Context) {}
