// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: fileflags/model.proto

package fileflags

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// ImplicitModelModel is the GORM model for fileflags.ImplicitModel.
type ImplicitModelModel struct {
}
