// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm 1.0.0
// 	protoc          (unknown)
// source: fileflags/modelflag.proto

package fileflags

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// ModelFlagMessageModel is the GORM model for fileflags.ModelFlagMessage.
type ModelFlagMessageModel struct {
}

// ToProto converts a ModelFlagMessageModel to its protobuf representation.
func (m *ModelFlagMessageModel) ToProto() (*ModelFlagMessage, error) {
	p := new(ModelFlagMessage)
	return p, nil
}

// ToModel converts a ModelFlagMessage to its GORM model.
func (p *ModelFlagMessage) ToModel() (*ModelFlagMessageModel, error) {
	m := new(ModelFlagMessageModel)
	return m, nil
}
