// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: fileflags/modelflag.proto

package fileflags

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// ModelFlagMessageModel is the GORM model for fileflags.ModelFlagMessage.
type ModelFlagMessageModel struct {
}

// AsProto converts a ModelFlagMessageModel to its protobuf representation.
func (m *ModelFlagMessageModel) AsProto() (*ModelFlagMessage, error) {
	x := new(ModelFlagMessage)
	return x, nil
}

// AsModel converts a ModelFlagMessage to its GORM model.
func (x *ModelFlagMessage) AsModel() (*ModelFlagMessageModel, error) {
	m := new(ModelFlagMessageModel)
	return m, nil
}
