// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm 1.0.0
// 	protoc          (unknown)
// source: fileflags/validateflag.proto

package fileflags

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// ValidateFlagMessageModel is the GORM model for fileflags.ValidateFlagMessage.
type ValidateFlagMessageModel struct {
}

// ToProto converts a ValidateFlagMessageModel to its protobuf representation.
func (m *ValidateFlagMessageModel) ToProto() (*ValidateFlagMessage, error) {
	p := new(ValidateFlagMessage)
	return p, nil
}

// ToModel converts a ValidateFlagMessage to its GORM model.
func (p *ValidateFlagMessage) ToModel() (*ValidateFlagMessageModel, error) {
	m := new(ValidateFlagMessageModel)
	return m, nil
}
