// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: fileflags/validateflag.proto

package fileflags

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// ValidateFlagMessageModel is the GORM model for fileflags.ValidateFlagMessage.
type ValidateFlagMessageModel struct {
}

// AsProto converts a ValidateFlagMessageModel to its protobuf representation.
func (m *ValidateFlagMessageModel) AsProto() (*ValidateFlagMessage, error) {
	x := new(ValidateFlagMessage)
	return x, nil
}

// AsModel converts a ValidateFlagMessage to its GORM model.
func (x *ValidateFlagMessage) AsModel() (*ValidateFlagMessageModel, error) {
	m := new(ValidateFlagMessageModel)
	return m, nil
}
