// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: fileflags/validate.proto

package fileflags

import (
	context "context"
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// ImplicitValidateModel is the GORM model for fileflags.ImplicitValidate.
type ImplicitValidateModel struct {
}

// ToProto converts a ImplicitValidateModel to its protobuf representation.
func (m *ImplicitValidateModel) ToProto() (*ImplicitValidate, error) {
	x := new(ImplicitValidate)
	return x, nil
}

// ToModel converts a ImplicitValidate to its GORM model.
func (x *ImplicitValidate) ToModel() (*ImplicitValidateModel, error) {
	m := new(ImplicitValidateModel)
	return m, nil
}

func CreateImplicitValidateModel(ctx context.Context) {}

func GetImplicitValidateModel(ctx context.Context) {}

func ListImplicitValidateModel(ctx context.Context) {}

func UpdateImplicitValidateModel(ctx context.Context) {}

func DeleteImplicitValidateModel(ctx context.Context) {}
