// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: fieldtypes/fieldtypes.proto

package fieldtypes

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// MyMessageModel is the GORM model for fieldtypes.MyMessage.
type MyMessageModel struct {
	StringField string
}
