// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: fieldtypes/fieldtypes.proto

package fieldtypes

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	time "time"
)

// WithScalarValuesModel is the GORM model for fieldtypes.WithScalarValues.
type WithScalarValuesModel struct {
	DoubleField   float64
	FloatField    float32
	Int32Field    int32
	Int64Field    int64
	Uint32Field   uint32
	Uint64Field   uint64
	Sint32Field   int32
	Sint64Field   int64
	Fixed32Field  uint32
	Fixed64Field  uint64
	Sfixed32Field int32
	Sfixed64Field int64
	BoolField     bool
	StringField   string
	BytesField    []byte
}

// AsProto converts a WithScalarValuesModel to its protobuf representation.
func (m *WithScalarValuesModel) AsProto() (*WithScalarValues, error) {
	x := new(WithScalarValues)
	x.DoubleField = m.DoubleField
	x.FloatField = m.FloatField
	x.Int32Field = m.Int32Field
	x.Int64Field = m.Int64Field
	x.Uint32Field = m.Uint32Field
	x.Uint64Field = m.Uint64Field
	x.Sint32Field = m.Sint32Field
	x.Sint64Field = m.Sint64Field
	x.Fixed32Field = m.Fixed32Field
	x.Fixed64Field = m.Fixed64Field
	x.Sfixed32Field = m.Sfixed32Field
	x.Sfixed64Field = m.Sfixed64Field
	x.BoolField = m.BoolField
	x.StringField = m.StringField
	x.BytesField = m.BytesField
	return x, nil
}

// AsModel converts a WithScalarValues to its GORM model.
func (x *WithScalarValues) AsModel() (*WithScalarValuesModel, error) {
	m := new(WithScalarValuesModel)
	m.DoubleField = x.DoubleField
	m.FloatField = x.FloatField
	m.Int32Field = x.Int32Field
	m.Int64Field = x.Int64Field
	m.Uint32Field = x.Uint32Field
	m.Uint64Field = x.Uint64Field
	m.Sint32Field = x.Sint32Field
	m.Sint64Field = x.Sint64Field
	m.Fixed32Field = x.Fixed32Field
	m.Fixed64Field = x.Fixed64Field
	m.Sfixed32Field = x.Sfixed32Field
	m.Sfixed64Field = x.Sfixed64Field
	m.BoolField = x.BoolField
	m.StringField = x.StringField
	m.BytesField = x.BytesField
	return m, nil
}

// WithKnownTypesModel is the GORM model for fieldtypes.WithKnownTypes.
type WithKnownTypesModel struct {
	TimestampField time.Time
}

// AsProto converts a WithKnownTypesModel to its protobuf representation.
func (m *WithKnownTypesModel) AsProto() (*WithKnownTypes, error) {
	x := new(WithKnownTypes)
	if m.TimestampField != (time.Time{}) {
		x.TimestampField = timestamppb.New(m.TimestampField)
	}
	return x, nil
}

// AsModel converts a WithKnownTypes to its GORM model.
func (x *WithKnownTypes) AsModel() (*WithKnownTypesModel, error) {
	m := new(WithKnownTypesModel)
	if t := x.TimestampField; t != nil {
		m.TimestampField = t.AsTime()
	}
	return m, nil
}

// WithEnumModel is the GORM model for fieldtypes.WithEnum.
type WithEnumModel struct {
	EnumField int32
}

// AsProto converts a WithEnumModel to its protobuf representation.
func (m *WithEnumModel) AsProto() (*WithEnum, error) {
	x := new(WithEnum)
	x.EnumField = AnEnum(m.EnumField)
	return x, nil
}

// AsModel converts a WithEnum to its GORM model.
func (x *WithEnum) AsModel() (*WithEnumModel, error) {
	m := new(WithEnumModel)
	m.EnumField = int32(x.EnumField)
	return m, nil
}
