// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: modelflags/modelflags.proto

package modelflags

import (
	context "context"
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// ModelOptionModel is the GORM model for modelflags.ModelOption.
type ModelOptionModel struct {
}

// ToProto converts a ModelOptionModel to its protobuf representation.
func (m *ModelOptionModel) ToProto() ModelOption {
	panic(true)
}

// ToModel converts a ModelOption to its GORM model.
func (x *ModelOption) ToModel() ModelOptionModel {
	panic(true)
}

func CreateModelOptionModel(ctx context.Context) {}

func GetModelOptionModel(ctx context.Context) {}

func ListModelOptionModel(ctx context.Context) {}

func UpdateModelOptionModel(ctx context.Context) {}

func DeleteModelOptionModel(ctx context.Context) {}

// ValidateImpliesModelModel is the GORM model for modelflags.ValidateImpliesModel.
type ValidateImpliesModelModel struct {
}

// ToProto converts a ValidateImpliesModelModel to its protobuf representation.
func (m *ValidateImpliesModelModel) ToProto() ValidateImpliesModel {
	panic(true)
}

// ToModel converts a ValidateImpliesModel to its GORM model.
func (x *ValidateImpliesModel) ToModel() ValidateImpliesModelModel {
	panic(true)
}

func CreateValidateImpliesModelModel(ctx context.Context) {}

func GetValidateImpliesModelModel(ctx context.Context) {}

func ListValidateImpliesModelModel(ctx context.Context) {}

func UpdateValidateImpliesModelModel(ctx context.Context) {}

func DeleteValidateImpliesModelModel(ctx context.Context) {}

// CRUDImpliesModelModel is the GORM model for modelflags.CRUDImpliesModel.
type CRUDImpliesModelModel struct {
}

// ToProto converts a CRUDImpliesModelModel to its protobuf representation.
func (m *CRUDImpliesModelModel) ToProto() CRUDImpliesModel {
	panic(true)
}

// ToModel converts a CRUDImpliesModel to its GORM model.
func (x *CRUDImpliesModel) ToModel() CRUDImpliesModelModel {
	panic(true)
}

func CreateCRUDImpliesModelModel(ctx context.Context) {}

func GetCRUDImpliesModelModel(ctx context.Context) {}

func ListCRUDImpliesModelModel(ctx context.Context) {}

func UpdateCRUDImpliesModelModel(ctx context.Context) {}

func DeleteCRUDImpliesModelModel(ctx context.Context) {}
