// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm 1.0.0
// 	protoc          (unknown)
// source: tabler/tabler.proto

package tabler

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// ImplementsTablerModel is the GORM model for tabler.ImplementsTabler.
type ImplementsTablerModel struct {
}

// ToProto converts a ImplementsTablerModel to its protobuf representation.
func (m *ImplementsTablerModel) ToProto() (*ImplementsTabler, error) {
	p := new(ImplementsTabler)
	return p, nil
}

// ToModel converts a ImplementsTabler to its GORM model.
func (p *ImplementsTabler) ToModel() (*ImplementsTablerModel, error) {
	m := new(ImplementsTablerModel)
	return m, nil
}

func (m *ImplementsTablerModel) TableName() string {
	return "name"
}
