// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: fieldtags/fieldtags.proto

package fieldtags

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// OptionsModel is the GORM model for fieldtags.Options.
type OptionsModel struct {
	Column             string `gorm:"column:my_column"`
	NotNull            string `gorm:"not null"`
	Default            string `gorm:"default:value"`
	Unique             string `gorm:"unique"`
	PrimaryKey         string `gorm:"primaryKey"`
	DefaultIndex       string `gorm:"index"`
	NamedIndex         string `gorm:"index:my_index"`
	UniqueDefaultIndex string `gorm:"uniqueIndex"`
	UniqueNamedIndex   string `gorm:"uniqueIndex:my_unique_index"`
	AutoCreateTime     string `gorm:"autoCreateTime"`
	AutoUpdateTime     string `gorm:"autoUpdateTime"`
	Ignore             string `gorm:"-"`
}

// AsProto converts a OptionsModel to its protobuf representation.
func (m *OptionsModel) AsProto() (*Options, error) {
	x := new(Options)
	x.Column = m.Column
	x.NotNull = m.NotNull
	x.Default = m.Default
	x.Unique = m.Unique
	x.PrimaryKey = m.PrimaryKey
	x.DefaultIndex = m.DefaultIndex
	x.NamedIndex = m.NamedIndex
	x.UniqueDefaultIndex = m.UniqueDefaultIndex
	x.UniqueNamedIndex = m.UniqueNamedIndex
	x.AutoCreateTime = m.AutoCreateTime
	x.AutoUpdateTime = m.AutoUpdateTime
	x.Ignore = m.Ignore
	return x, nil
}

// AsModel converts a Options to its GORM model.
func (x *Options) AsModel() (*OptionsModel, error) {
	m := new(OptionsModel)
	m.Column = x.Column
	m.NotNull = x.NotNull
	m.Default = x.Default
	m.Unique = x.Unique
	m.PrimaryKey = x.PrimaryKey
	m.DefaultIndex = x.DefaultIndex
	m.NamedIndex = x.NamedIndex
	m.UniqueDefaultIndex = x.UniqueDefaultIndex
	m.UniqueNamedIndex = x.UniqueNamedIndex
	m.AutoCreateTime = x.AutoCreateTime
	m.AutoUpdateTime = x.AutoUpdateTime
	m.Ignore = x.Ignore
	return m, nil
}

// DenyOptionsModel is the GORM model for fieldtags.DenyOptions.
type DenyOptionsModel struct {
	Ignore     string `gorm:"-"`
	UpdateOnly string `gorm:"->:false;<-:update"`
	CreateOnly string `gorm:"->:false;<-:create"`
	WriteOnly  string `gorm:"->:false;<-"`
	ReadOnly   string `gorm:"->"`
	ReadUpdate string `gorm:"<-:update"`
	ReadCreate string `gorm:"<-:create"`
}

// AsProto converts a DenyOptionsModel to its protobuf representation.
func (m *DenyOptionsModel) AsProto() (*DenyOptions, error) {
	x := new(DenyOptions)
	x.Ignore = m.Ignore
	x.UpdateOnly = m.UpdateOnly
	x.CreateOnly = m.CreateOnly
	x.WriteOnly = m.WriteOnly
	x.ReadOnly = m.ReadOnly
	x.ReadUpdate = m.ReadUpdate
	x.ReadCreate = m.ReadCreate
	return x, nil
}

// AsModel converts a DenyOptions to its GORM model.
func (x *DenyOptions) AsModel() (*DenyOptionsModel, error) {
	m := new(DenyOptionsModel)
	m.Ignore = x.Ignore
	m.UpdateOnly = x.UpdateOnly
	m.CreateOnly = x.CreateOnly
	m.WriteOnly = x.WriteOnly
	m.ReadOnly = x.ReadOnly
	m.ReadUpdate = x.ReadUpdate
	m.ReadCreate = x.ReadCreate
	return m, nil
}
