// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: fileflagvalidate/validate.proto

package fileflagvalidate

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// MyMessageModel is the GORM model for fileflagvalidate.MyMessage.
type MyMessageModel struct {
}

// AsProto converts a MyMessageModel to its protobuf representation.
func (m *MyMessageModel) AsProto() (*MyMessage, error) {
	x := new(MyMessage)
	return x, nil
}

// AsModel converts a MyMessage to its GORM model.
func (x *MyMessage) AsModel() (*MyMessageModel, error) {
	m := new(MyMessageModel)
	return m, nil
}
