// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: models.proto

package pb

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	time "time"
)

// FileModel is the GORM model for pb.File.
type FileModel struct {
	Uuid    string    `gorm:"not null;unique;primaryKey"`
	Name    string    `gorm:"not null;index"`
	Bytes   int64     `gorm:"not null"`
	Created time.Time `gorm:"not null;autoCreateTime;<-:create"`
	Updated time.Time `gorm:"autoUpdateTime"`
}

// AsProto converts a FileModel to its protobuf representation.
func (m *FileModel) AsProto() (*File, error) {
	x := new(File)
	x.Uuid = m.Uuid
	x.Name = m.Name
	x.Bytes = m.Bytes
	if m.Created != (time.Time{}) {
		x.Created = timestamppb.New(m.Created)
	}
	if m.Updated != (time.Time{}) {
		x.Updated = timestamppb.New(m.Updated)
	}
	return x, nil
}

// AsModel converts a File to its GORM model.
func (x *File) AsModel() (*FileModel, error) {
	m := new(FileModel)
	m.Uuid = x.Uuid
	m.Name = x.Name
	m.Bytes = x.Bytes
	if t := x.Created; t != nil {
		m.Created = t.AsTime()
	}
	if t := x.Updated; t != nil {
		m.Updated = t.AsTime()
	}
	return m, nil
}

func (m *FileModel) TableName() string {
	return "localfiles"
}
