// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: customtypes/customtypes.proto

package customtypes

import (
	context "context"
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// WithInlineJsonModel is the GORM model for customtypes.WithInlineJson.
type WithInlineJsonModel struct {
	MessageField       string
	NestedMessageField string
	MapField           string
	RepeatedField      string
	StringField        string
	Int32Field         string
	BoolField          string
}

// ToProto converts a WithInlineJsonModel to its protobuf representation.
func (m *WithInlineJsonModel) ToProto() WithInlineJson {
	panic(true)
}

// ToModel converts a WithInlineJson to its GORM model.
func (x *WithInlineJson) ToModel() WithInlineJsonModel {
	panic(true)
}

func CreateWithInlineJsonModel(ctx context.Context) {}

func GetWithInlineJsonModel(ctx context.Context) {}

func ListWithInlineJsonModel(ctx context.Context) {}

func UpdateWithInlineJsonModel(ctx context.Context) {}

func DeleteWithInlineJsonModel(ctx context.Context) {}
