// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          (unknown)
// source: customtypes/customtypes.proto

package customtypes

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb"
)

// WithInlineJsonModel is the GORM model for customtypes.WithInlineJson.
type WithInlineJsonModel struct {
	MessageField       string
	NestedMessageField string
	MapField           string
	RepeatedField      string
	StringField        string
	Int32Field         string
	BoolField          string
}
