// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// 	protoc-gen-gorm v0.0.0
// 	protoc          v3.17.3
// source: modelflags/modelflags.proto

package modelflags

import (
	_ "github.com/complex64/protoc-gen-gorm/gormpb/v2"
)

// MyMessageModel is the GORM model for modelflags.MyMessage.
type MyMessageModel struct {
}

// MyHooksMessageModel is the GORM model for modelflags.MyHooksMessage.
type MyHooksMessageModel struct {
}

// MyValidateMessageModel is the GORM model for modelflags.MyValidateMessage.
type MyValidateMessageModel struct {
}

// MyCrudMessageModel is the GORM model for modelflags.MyCrudMessage.
type MyCrudMessageModel struct {
}
