name: Tests
on:
  push:
    tags:
      - v*
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/mkdocs.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/mkdocs.yml'
jobs:
  test:
    name: unit
    strategy:
      matrix:
        go-version:
          - 1.17
          - 1.18
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      # Set cache paths.
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      # Cache builds; speedup tests.
      - name: Build Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      # Cache modules; speedup builds.
      - name: Module Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
      - name: Run Tests
        run: go test -race -coverprofile=coverage.out ./...
